# Generated by Django 4.1.7 on 2024-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
