# Generated by Django 4.1.7 on 2024-11-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="last_login",
            field=models.DateTimeField(null=True),
        ),
    ]
